### ISSUE TITLE
(UndefinedFunctionError) function :inets.stop/2 is undefined (module :inets is not available)

### ISSUE THREAD

**Issue by zanhsieh** [msaraiva/docker-alpine#14]
Hi,

Just curious how I should fix this error?

```
$ docker images
REPOSITORY                           TAG                  IMAGE ID            CREATED             SIZE
......
msaraiva/elixir                      latest               059bf893a35a        7 weeks ago         23.79 MB
......

$ docker run --rm -it msaraiva/elixir ash
/ # mkdir test
/ # cd test
/test # mix local.hex
** (UndefinedFunctionError) function :inets.stop/2 is undefined (module :inets is not available)
    :inets.stop(:httpc, :mix)
    (mix) lib/mix/utils.ex:419: Mix.Utils.read_httpc/1
    (mix) lib/mix/utils.ex:364: Mix.Utils.read_path/2
    (mix) lib/mix/local.ex:139: Mix.Local.read_path!/2
    (mix) lib/mix/local.ex:118: Mix.Local.find_matching_versions_from_signed_csv!/2
    (mix) lib/mix/tasks/local.hex.ex:29: Mix.Tasks.Local.Hex.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Did I do something wrong?

**Comment by XOfSpades** [comment]
I ran into the same issue. This helped me resolving it: 
[msaraiva/elixir](https://hub.docker.com/r/msaraiva/elixir/builds/btfqtcphccbs4dzg8wzryzp/)

Just add
`RUN apk --update add elixir wget git && rm -rf /var/cache/apk/*` to your Dockerfile
